spring:
  profiles: peer1
server:
  port: 9200
---
spring:
  profiles: peer2
server:
  port: 9222
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/
  instance:
    preferIpAddress: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
